# Generated by Django 6.0.5 on 2026-06-02 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='appointments.profissional')),
            ],
        ),
    ]
