name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, staging ]
  pull_request:
    branches: [ main, master, staging ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    
    env:
      SECRET_KEY: "django-insecure-test-key-healthcare-appointments-api"
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
      DB_HOST: "localhost"
      DB_PORT: "5432"

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Poetry
      run: |
        pip install poetry
        poetry config virtualenvs.create false

    - name: Install dependencies
      run: poetry install --no-interaction --no-root

    # STEP OBRIGATÓRIO 1: LINT
    - name: Run Lint (Ruff check)
      run: |
        pip install ruff
        ruff check .

    # STEP OBRIGATÓRIO 2: TESTES
    - name: Run Tests
      run: |
        python manage.py test


  build-and-deploy:
    needs: test-and-lint # Só roda se o Lint e os Testes passarem!
    runs-on: ubuntu-latest
    # Garante que o deploy real em nuvem só aconteça ao fazer push/merge (ignora Pull Requests abertos)
    if: github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # STEP OBRIGATÓRIO 3: BUILD (Compilação e validação do Container Docker do ecossistema)
    - name: Build Docker Image
      run: |
        echo "Iniciando Step de Build exigido pelo Edital..."
        docker build -t healthcare-appointments-api:${{ github.sha }} .
        echo "Build da imagem Docker concluído com sucesso para a tag ${{ github.sha }}!"

    # STEP OBRIGATÓRIO 4: DEPLOY INTELIGENTE (Separação de Staging e Produção via Render)
    - name: Deploy to Cloud Environment (Render Hub)
      run: |
        if [ "${{ github.ref }}" = "refs/heads/main" ] || [ "${{ github.ref }}" = "refs/heads/master" ]; then
          echo "🎯 Branch identificada: [MAIN/MASTER]"
          echo "🚀 Disparando Deploy Automatizado para o Ambiente de PRODUÇÃO..."
          # Aqui faz a chamada real via cURL usando o Deploy Hook que o Render te dá nas configurações do serviço
          curl -fX POST "${{ secrets.RENDER_DEPLOY_HOOK_PRODUCTION }}"
        else
          echo "🧪 Branch identificada: [${{ github.ref }}]"
          echo "🛠️ Disparando Deploy Automatizado para o Ambiente de STAGING..."
          # Aqui faz a chamada para o webhook do seu segundo app (o de Staging) no Render
          curl -fX POST "${{ secrets.RENDER_DEPLOY_HOOK_STAGING }}"
        fi